CODIFICAÇÃO/app/controllers/auth_controller.py
from flask import Blueprint, render_template, redirect, url_for, flash, session
from app.forms import SignupForm, LoginForm
from app.models.user import User
from app import db

bp = Blueprint("auth", __name__, url_prefix="/auth")


@bp.route("/signup", methods=["GET", "POST"])
def signup():
    form = SignupForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash("Cadastrado, agora voce pode entrar para o Clã!")
        return redirect(url_for("auth.login"))
    return render_template("auth/signup.html", title="Sign Up", form=form)


@bp.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            flash("Invalid username or password")
            return redirect(url_for("auth.login"))
        session["username"] = form.username.data
        return redirect(url_for("main.principal"))
    return render_template("auth/login.html", title="Sign In", form=form)


@bp.route("/logout")
def logout():
    session.pop("username", None)
    return redirect(
        url_for("main.index")
    )  # Redireciona para a rota principal após o logout

CODIFICAÇÃO/app/controllers/main_controller.py

from flask import Blueprint, render_template, redirect, url_for, flash,session
from app.forms import SignupForm, LoginForm
from functools import wraps

bp = Blueprint('main', __name__,template_folder='templates/main')

def verificar_autenticacao(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'username' not in session or session.get('username') is None:
            flash('Você precisa fazer login para acessar esta página.', 'warning')
            return redirect(url_for('auth.login'))
        return f(*args, **kwargs)
    return decorated_function

@bp.route('/')
def index():
    return render_template('index.html')

@bp.route('/principal')
@verificar_autenticacao
def principal():
        return render_template('main/principal.html')
    
    
@bp.route('/usuario')
@verificar_autenticacao
def usuario():  
        return render_template('main/usuario.html')
   

@bp.route('/rank')
@verificar_autenticacao
def rank():
        return render_template('main/rank.html')
    

CODIFICAÇÃO/app/controllers/questionario_controller.py
from flask import render_template, request, session
from flask import Blueprint, redirect, url_for, flash
from app.models.openia_questionario import OpeniaQuestionario

openia_questionario = OpeniaQuestionario(api_key="")

bp = Blueprint("quest", __name__, url_prefix="/quest")

@bp.route("/gerar", methods=["POST"])
def gerar_questionario():
    tema = request.form["tema"]
    perguntas = openia_questionario.gerar_perguntas(tema)
    print(f"Perguntas geradas: {perguntas}")

    respostas = openia_questionario.obter_respostas_chat(tema)
    print(f"Respostas do chat na rota gerar_questionario: {respostas}")

    session['respostas'] = respostas
    return render_template("quest/gerar.html", perguntas=perguntas)



@bp.route("/processar", methods=["POST"])
def processar_respostas():
    respostas_submetidas = request.form
    respostas_corretas = session.get('respostas')

    print(f"Respostas submetidas dentro do processar_respostas: {respostas_submetidas}")
    print(f"Respostas corretas fornecidas pela API dentro do processar respostas: {respostas_corretas}")

    if respostas_corretas:
        resultados, acertos = openia_questionario.verificar_respostas(respostas_submetidas, respostas_corretas)
        print(f"Resultados: {resultados}, Acertos: {acertos}")
    else:
        resultados = None
        acertos = 0

    return render_template("quest/processar.html", resultados=resultados, acertos=acertos)

CODIFICAÇÃO/app/templates/quest/gerar.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Questionário</title>
    <style>
        .pergunta {
            margin-bottom: 20px;
        }

        .alternativa {
            margin-left: 20px;
        }
    </style>
</head>

<body>
    <h1>Questionário</h1>
    <form action="{{ url_for('quest.processar_respostas') }}" method="post">
        {% for pergunta, opcoes in perguntas %}
        <div class="pergunta">
            <p>{{ pergunta }}</p>
            {% for opcao in opcoes %}
            <div class="alternativa">
                <input type="radio" id="{{ opcao }}" name="{{ pergunta }}" value="{{ opcao }}">
                <label for="{{ opcao }}">{{ opcao }}</label>
            </div>
            {% endfor %}
        </div>
        {% endfor %}

        <button type="submit">Enviar Respostas</button>
    </form>
</body>

</html>

CODIFICAÇÃO/app/templates/quest/processar.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='images/icons/favicon.ico') }}" />
    <!--===============================================================================================-->

    <link rel="stylesheet" type="text/css"
        href="{{ url_for('static', filename='fonts/font-awesome-4.7.0/css/font-awesome.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='vendor/animate/animate.css') }}">
    <link rel="stylesheet" type="text/css"
        href="{{ url_for('static', filename='vendor/css-hamburgers/hamburgers.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='vendor/select2/select2.min.css') }}">
    <!-- <link href="{{ url_for('static', filename='/css/bootstrap.css') }}" rel="stylesheet"> -->


    <!--===============================================================================================-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/util.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='/css/meu.css') }}">

    <title>Hackers School</title>
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <div class=""></div>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="nav navbar-nav">
                <img class="imgLogo" src="{{ url_for('static', filename='images/icons/icone1.png')}}" alt="logo">
            </div>

            <div class="navbar-nav logotipo">
                <a class="navbar-brand" href="#">Hackers School</a>

            </div>

            <ul class="nav navbar-nav">
                <li class="active"><a class="nav-link active text-white btn btn-secondary btn-lg"
                        href="{{ url_for('main.index') }}">Home</a>
                </li>
                <li><a class="nav-link active text-white btn btn-secondary btn-lg"
                        href="{{ url_for('auth.login') }}">Login</a></li>
                <li> <a class="nav-link text-white btn btn-secondary btn-lg"
                        href="{{ url_for('auth.signup') }}">Cadastro</a></li>
                <li><a class="nav-link text-white btn btn-secondary btn-lg"
                        href="{{ url_for('main.usuario') }}">Perfil</a></li>
                <li> <a class="nav-link text-white btn btn-secondary btn-lg" href="{{ url_for('main.rank') }}">Rank</a>
                </li>
                <li><a class="nav-link text-white btn btn-secondary btn-lg"
                        href="{{ url_for('main.principal') }}">Quiz</a>
                </li>

            </ul>
            <ul class="nav navbar-nav navbar-right"> {% if 'username' in session %}
                <li><a href="{{ url_for('main.rank') }}"><span class="btn"></span>
                        <img class="imgRank" src="{{ url_for('static', filename='images/rank/24.png')}}" alt="rank24">
                        <span>Usuário: {{ session['username'] }}</span></a></li>
                {% endif %}
                <li><a class="nav-link text-white btn" href="{{ url_for('auth.logout') }}"><span
                            class="glyphicon glyphicon-log-in"></span> Sair</a></li>



            </ul>
        </div>
    </nav>

    <div class="">
        <div class="">
            <h1 class="">Resultados do Questionário</h1>
        </div>

        <div class="">
            <table border="2" class="table tamanhoTable">
                <tr class=" tableCor  center">
                    <th scope="col" class="text-center thCor">Pergunta</th>
                    <th scope="col" class="text-center thCor">Sua Resposta</th>
                    <th scope="col" class="text-center thCor">Resposta Correta</th>
                    <th scope="col" class="text-center thCor">Correto?</th>
                </tr>
                {% for resultado in resultados %}
                <tr>
                    <td class="thCor">{{ resultado[0] }}</td>
                    <td class="thCor">{{ resultado[1] }}</td>
                    <td class="thCor">{{ resultado[2] }}</td>
                    <td class="thCor">{% if resultado[3] %}Sim{% else %}Não{% endif %}</td>
                </tr>
                {% endfor %}
            </table>
        </div>

        <p>Total de acertos: {{ acertos }}</p>
    </div>

    <script src=" {{ url_for('static', filename='vendor/jquery/jquery-3.2.1.min.js' ) }}">
    </script>
    <script src="{{ url_for('static', filename='vendor/bootstrap/js/popper.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/select2/select2.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/tilt/tilt.jquery.min.js') }}"></script>
    <!-- <script src="{{ url_for('static', filename='js/bootstrap.js') }}"></script> -->

    <script>
        $('.js-tilt').tilt({
            scale: 1.1
        })
    </script>
    <!--===============================================================================================-->
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
</body>

</html>

</html>