CODIFICAÇÃO/app/controllers/main_controller.py

from flask import Blueprint, render_template, redirect, url_for, flash,session
from app.forms import SignupForm, LoginForm
from functools import wraps

bp = Blueprint('main', __name__,template_folder='templates/main')

def verificar_autenticacao(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'username' not in session or session.get('username') is None:
            flash('Você precisa fazer login para acessar esta página.', 'warning')
            return redirect(url_for('auth.login'))
        return f(*args, **kwargs)
    return decorated_function

@bp.route('/')
def index():
    return render_template('index.html')

@bp.route('/principal')
@verificar_autenticacao
def principal():
        return render_template('main/principal.html')
    
    
@bp.route('/usuario')
@verificar_autenticacao
def usuario():  
        return render_template('main/usuario.html')
   

@bp.route('/rank')
@verificar_autenticacao
def rank():
        return render_template('main/rank.html')
    

CODIFICAÇÃO/app/controllers/questionario_controller.py
from flask import render_template, request, session
from flask import Blueprint, redirect, url_for, flash
from app.models.openia_questionario import OpeniaQuestionario

openia_questionario = OpeniaQuestionario(api_key="")

bp = Blueprint("quest", __name__, url_prefix="/quest")

@bp.route("/gerar", methods=["POST"])
def gerar_questionario():
    tema = request.form["tema"]
    perguntas = openia_questionario.gerar_perguntas(tema)
    print(f"Perguntas geradas: {perguntas}")

    respostas = openia_questionario.obter_respostas_chat(tema)
    print(f"Respostas do chat na rota gerar_questionario: {respostas}")

    session['respostas'] = respostas
    return render_template("quest/gerar.html", perguntas=perguntas)



@bp.route("/processar", methods=["POST"])
def processar_respostas():
    respostas_submetidas = request.form
    respostas_corretas = session.get('respostas')

    print(f"Respostas submetidas dentro do processar_respostas: {respostas_submetidas}")
    print(f"Respostas corretas fornecidas pela API dentro do processar respostas: {respostas_corretas}")

    if respostas_corretas:
        resultados, acertos = openia_questionario.verificar_respostas(respostas_submetidas, respostas_corretas)
        print(f"Resultados: {resultados}, Acertos: {acertos}")
    else:
        resultados = None
        acertos = 0

    return render_template("quest/processar.html", resultados=resultados, acertos=acertos)

CODIFICAÇÃO/app/templates/main/principal.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Escolha o tema</title>
</head>

<body>
    <div class="container container1 mt-4">
        <h1 class="mb-4 text-black">Escolha o tema para gerar o questionário:</h1>
        <form action="{{ url_for('quest.gerar_questionario') }}" method="post" class="row g-3 ">
            <div class="col-md-6 ">
                <select name="tema" class="form-select form-control input100">
                    <option value="software">Software</option>
                    <option value="informatica">Informática</option>
                    <option value="tecnologia">Tecnologia</option>
                    <option value="programacao">Programação</option>
                    <option value="design">Design</option>
                    <option value="hardware">Hardware</option>
                    <option value="redes">Redes</option>
                    <option value="seguranca_da_informacao">Segurança da Informação</option>
                    <option value="banco_de_dados">Banco de Dados</option>
                    <option value="sistemas_operacionais">Sistemas Operacionais</option>
                    <option value="internet">Internet</option>
                    <option value="web">Web</option>
                    <option value="mobile">Mobile</option>
                    <option value="cloud_computing">Cloud Computing</option>
                    <option value="inteligencia_artificial">Inteligência Artificial</option>
                    <option value="robotica">Robótica</option>
                    <option value="impressao_3d">Impressão 3D</option>
                    <option value="realidade_virtual">Realidade Virtual</option>
                    <option value="realidade_aumentada">Realidade Aumentada</option>
                    <option value="internet_das_coisas">Internet das Coisas</option>
                    <option value="big_data">Big Data</option>
                    <option value="machine_learning">Machine Learning</option>
                    <option value="chatbots">Chatbots</option>
                    <option value="blockchain">Blockchain</option>
                    <option value="linguagens_de_programacao">Linguagens de Programação</option>
                    <option value="python">Python</option>
                    <option value="java">Java</option>
                    <option value="javascript">JavaScript</option>
                    <option value="c++">C++</option>
                    <option value="c#">C#</option>
                    <option value="php">PHP</option>
                    <option value="ruby">Ruby</option>
                    <option value="swift">Swift</option>
                    <option value="go">Go</option>
                    <option value="ux">UX</option>
                    <option value="ui">UI</endoption>
                    <option value="design_grafico">Design Gráfico</option>
                    <option value="web_design">Web Design</option>
                    <option value="design_de_interacao">Design de Interação</option>
                    <option value="design_de_experiencia_do_usuario">Design de Experiência do Usuário</option>
                    <option value="tipografia">Tipografia</option>
                    <option value="paleta_de_cores">Paleta de Cores</option>
                    <option value="design_de_produto">Design de Produto</option>
                    <option value="design_de_servico">Design de Serviço</option>
                </select>
            </div>

            <div class="col-md-6">
                <button type="submit" class="btn btn-primary btn-lg">Gerar Questionário</button>
            </div>

        </form>
    </div>

</body>

</html>

{% endblock %}

CODIFICAÇÃO/app/templates/main/rank.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}

<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='/css/rank.css') }}">

<div class="container mt-4">
    <div class="row justify-content-center mt-4 ">
        <!-- Primeiro colocado -->
        <div class="col-lg-4">
            <div class="card first-place">
                <div class="card-body">
                    <div class="ranks">
                        <h3 class="mb-0">Thiago Barros Gomes</h3>
                        <img class="imgRankMaster" src="{{ url_for('static', filename='images/rank/24.png')}}"
                            alt="rank master" title="Rank Master">
                    </div>
                    <h5 class="card-title">Thiago Barros Gomes</h5>
                    <p class="card-text">Pontos 230</p>
                </div>
            </div>
        </div>
        <!-- Segundo colocado -->
        <div class="col-lg-4">
            <div class="card second-place">
                <div class="card-body">
                    <div class="ranks">
                        <h3 class="mb-0">Pedro Otavio</h3>
                        <img class="imgRankSecond" src="{{ url_for('static', filename='images/rank/23.png')}}"
                            alt="rank master" title="Rank Master">
                    </div>
                    <h5 class="card-title">Thiago Barros Gomes</h5>
                    <p class="card-text">Pontos 225</p>
                </div>
            </div>
        </div>
        <!-- Terceiro colocado -->
        <div class="col-lg-4">
            <div class="card third-place">
                <div class="card-body">
                    <div class="ranks">
                        <h3 class="mb-0">Guilherme Afonso</h3>
                        <img class="imgRankTirth" src="{{ url_for('static', filename='images/rank/22.png')}}"
                            alt="rank master" title="Rank Master">
                    </div>
                    <p class="card-text">Pontos 200</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-4">
        <!-- Quarto colocado -->
        <div class="col-lg-3">
            <div class="card other-place">
                <div class="card-body">
                    <h5 class="card-title">Quarto Colocado</h5>
                    <img class="imgRankAll" src="{{ url_for('static', filename='images/rank/21.png')}}"
                        alt="rank master" title="Rank Master">
                    <p class="card-text">Pontos 188</p>
                </div>
            </div>
        </div>
        <!-- Quinto colocado -->

        <div class="col-lg-3">
            <div class="card other-place">
                <div class="card-body">
                    <h5 class="card-title">Quarto Colocado</h5>
                    <img class="imgRankAll" src="{{ url_for('static', filename='images/rank/20.png')}}"
                        alt="rank master" title="Rank Master">
                    <p class="card-text">Pontos 188</p>
                </div>
            </div>
        </div>
        <!-- Sexto colocado -->
        <div class="col-lg-3">
            <div class="card other-place">
                <div class="card-body">
                    <h5 class="card-title">Quarto Colocado</h5>
                    <img class="imgRankAll" src="{{ url_for('static', filename='images/rank/19.png')}}"
                        alt="rank master" title="Rank Master">
                    <p class="card-text">Pontos 188</p>
                </div>
            </div>
        </div>
        <!-- Sétimo colocado -->
        <div class="col-lg-3">
            <div class="card other-place">
                <div class="card-body">
                    <h5 class="card-title">Quarto Colocado</h5>
                    <img class="imgRankAll" src="{{ url_for('static', filename='images/rank/18.png')}}"
                        alt="rank master" title="Rank Master">
                    <p class="card-text">Pontos 188</p>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

CODIFICAÇÃO/app/templates/main/usuario.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}

<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='/css/user.css') }}">

<div class="container mt-4">
    <div class="card p-4">
        <div class="mt-5 text-center">
            <h2 class="mb-0">Thiago Barros Gomes</h2>
            <span class="text-muted d-block mb-2">Araras</span>

            <div class="d-flex justify-content-between align-items-center mt-4 px-4">
                <div class="stats">
                    <h6 class="mb-0">Pontos</h6>
                    <span class="">230</span>
                </div>
                <div class="ranks">
                    <h3 class="mb-0">Ranks Adquiridos!</h3>
                    <img src="{{ url_for('static', filename='images/rank/1.png')}}" alt="rank master"
                        title="Rank Master">
                    <img src="{{ url_for('static', filename='images/rank/2.png')}}" alt="rank master"
                        title="Rank Master">
                    <img src="{{ url_for('static', filename='images/rank/3.png')}}" alt="rank master"
                        title="Rank Master">
                    <img src="{{ url_for('static', filename='images/rank/4.png')}}" alt="rank master"
                        title="Rank Master">
                    <img src="{{ url_for('static', filename='images/rank/5.png')}}" alt="rank master"
                        title="Rank Master">
                    <img src="{{ url_for('static', filename='images/rank/6.png')}}" alt="rank master"
                        title="Rank Master">
                    <img src="{{ url_for('static', filename='images/rank/7.png')}}" alt="rank master"
                        title="Rank Master">
                    <img src="{{ url_for('static', filename='images/rank/8.png')}}" alt="rank master"
                        title="Rank Master">
                    <img src="{{ url_for('static', filename='images/rank/9.png')}}" alt="rank master"
                        title="Rank Master">
                    <img src="{{ url_for('static', filename='images/rank/10.png')}}" alt="rank master"
                        title="Rank Master">
                    <img src="{{ url_for('static', filename='images/rank/11.png')}}" alt="rank master"
                        title="Rank Master">
                    <img src="{{ url_for('static', filename='images/rank/12.png')}}" alt="rank master"
                        title="Rank Master">
                    <img src="{{ url_for('static', filename='images/rank/13.png')}}" alt="rank master"
                        title="Rank Master">
                    <img src="{{ url_for('static', filename='images/rank/14.png')}}" alt="rank master"
                        title="Rank Master">
                    <img src="{{ url_for('static', filename='images/rank/15.png')}}" alt="rank master"
                        title="Rank Master">
                    <img src="{{ url_for('static', filename='images/rank/16.png')}}" alt="rank master"
                        title="Rank Master">
                    <img src="{{ url_for('static', filename='images/rank/17.png')}}" alt="rank master"
                        title="Rank Master">
                    <img src="{{ url_for('static', filename='images/rank/18.png')}}" alt="rank master"
                        title="Rank Master">
                    <img src="{{ url_for('static', filename='images/rank/19.png')}}" alt="rank master"
                        title="Rank Master">
                    <img src="{{ url_for('static', filename='images/rank/20.png')}}" alt="rank master"
                        title="Rank Master">
                    <img src="{{ url_for('static', filename='images/rank/21.png')}}" alt="rank master"
                        title="Rank Master">
                    <img src="{{ url_for('static', filename='images/rank/22.png')}}" alt="rank master"
                        title="Rank Master">
                    <img src="{{ url_for('static', filename='images/rank/23.png')}}" alt="rank master"
                        title="Rank Master">
                    <img src="{{ url_for('static', filename='images/rank/24.png')}}" alt="rank master"
                        title="Rank Master">

                    <!-- Adicione os outros logos de rank aqui -->
                </div>
            </div>
        </div>
        <button class="btn btn-primary btn-sm follow text-dark">Redes Sociais</button>
    </div>
</div>

{% endblock %}